# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='breed',
            field=models.CharField(default='Labrador', max_length=255),
        ),
    ]
