# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_userpref_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpref',
            name='breed',
        ),
    ]
