# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_remove_userpref_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(default='u', max_length=1),
        ),
    ]
