# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0010_auto_20180730_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='users',
        ),
        migrations.AlterField(
            model_name='userdog',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='pugorugh.Dog'),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
