# Generated by Django 2.0.6 on 2018-08-07 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0011_auto_20180807_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dog', to='pugorugh.Dog'),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dog', to=settings.AUTH_USER_MODEL),
        ),
    ]
